import { TeamType } from "./types";

import Breda from "./assets/teams/NACBreda.png";
import PSV from "./assets/teams/JongPsv.png";
import Helmont from "./assets/teams/HelmondSport.png";
import Ajax from "./assets/teams/JongAjax.png";
import Eidhoven from "./assets/teams/Eindhoven.png";
import Graafschap from "./assets/teams/Graafschap.png";
import Dondrecht from "./assets/teams/Dondrecht.png";
import Utrecht from "./assets/teams/JongUtrecht.png";
import Cambuur from "./assets/teams/Cambuur.png";

export const data: TeamType[] = [
  {
    name: "NAC Breda",
    manager: "levani619",
    logo: Breda,
    win: 1,
    draw: 0,
    lose: 0,
    points: 3,
    gf: 5,
    ga: 0,
    gd: 5,
    form: ["w"],
  },
  {
    name: "Jong PSV",
    manager: "luka messi 10",
    logo: PSV,
    win: 1,
    draw: 0,
    lose: 0,
    points: 3,
    gf: 5,
    ga: 1,
    gd: 4,
    form: ["w"],
  },
  {
    name: "Helmond Sport",
    manager: "თონისპატრონი",
    logo: Helmont,
    win: 1,
    draw: 0,
    lose: 0,
    points: 3,
    gf: 4,
    ga: 0,
    gd: 4,
    form: ["w"],
  },
  {
    name: "Jong Ajax",
    manager: "nikanoza",
    logo: Ajax,
    win: 1,
    draw: 0,
    lose: 0,
    points: 3,
    gf: 4,
    ga: 1,
    gd: 3,
    form: ["w"],
  },
  {
    name: "FC Eindhoven",
    manager: "chuvaka_77",
    logo: Eidhoven,
    win: 1,
    draw: 0,
    lose: 0,
    points: 3,
    gf: 3,
    ga: 2,
    gd: 1,
    form: ["w"],
  },
  {
    name: "De Graafschap",
    manager: "romafr_6",
    logo: Graafschap,
    win: 1,
    draw: 0,
    lose: 0,
    points: 3,
    gf: 1,
    ga: 0,
    gd: 1,
    form: ["w"],
  },
  {
    name: "FC Dordrecht",
    manager: "teimuraz",
    logo: Dondrecht,
    win: 1,
    draw: 0,
    lose: 0,
    points: 3,
    gf: 1,
    ga: 0,
    gd: 1,
    form: ["w"],
  },
  {
    name: "Jong FC Utrecht",
    manager: "lashuna",
    logo: Utrecht,
    win: 1,
    draw: 0,
    lose: 0,
    points: 3,
    gf: 1,
    ga: 0,
    gd: 1,
    form: ["w"],
  },
  {
    name: "SC Cambuur",
    manager: "nikaluka_7",
    logo: Cambuur,
    win: 1,
    draw: 0,
    lose: 0,
    points: 3,
    gf: 1,
    ga: 0,
    gd: 1,
    form: ["w"],
  },
];
