import { TeamType } from "./types";

import Breda from "./assets/teams/NACBreda.png";
import PSV from "./assets/teams/JongPsv.png";
import Helmont from "./assets/teams/HelmondSport.png";
import Ajax from "./assets/teams/JongAjax.png";
import Eidhoven from "./assets/teams/Eindhoven.png";
import Graafschap from "./assets/teams/Graafschap.png";
import Dondrecht from "./assets/teams/Dondrecht.png";
import Utrecht from "./assets/teams/JongUtrecht.png";
import Cambuur from "./assets/teams/Cambuur.png";
import Bosch from "./assets/teams/DenBosch.png";
import Venlo from "./assets/teams/Venlo.png";
import Emmen from "./assets/teams/Emmen.png";
import Groningen from "./assets/teams/Groningen.png";
import AZ from "./assets/teams/JongAZ.png";
import Telstar from "./assets/teams/Telstar.png";
import TopOss from "./assets/teams/TopOss.png";
import MVV from "./assets/teams/MVV.png";
import Willem from "./assets/teams/willem.png";
import DenHaag from "./assets/teams/AdoDenHaag.png";
import Roda from "./assets/teams/Roda.png";

export const data: TeamType[] = [
  {
    name: "NAC Breda",
    manager: "levani619",
    logo: Breda,
    win: 1,
    draw: 0,
    lose: 0,
    points: 3,
    gf: 5,
    ga: 0,
    gd: 5,
    form: ["w"],
  },
  {
    name: "Jong PSV",
    manager: "luka messi 10",
    logo: PSV,
    win: 1,
    draw: 0,
    lose: 0,
    points: 3,
    gf: 5,
    ga: 1,
    gd: 4,
    form: ["w"],
  },
  {
    name: "Helmond Sport",
    manager: "თონისპატრონი",
    logo: Helmont,
    win: 1,
    draw: 0,
    lose: 0,
    points: 3,
    gf: 4,
    ga: 0,
    gd: 4,
    form: ["w"],
  },
  {
    name: "Jong Ajax",
    manager: "nikanoza",
    logo: Ajax,
    win: 1,
    draw: 0,
    lose: 0,
    points: 3,
    gf: 4,
    ga: 1,
    gd: 3,
    form: ["w"],
  },
  {
    name: "FC Eindhoven",
    manager: "chuvaka_77",
    logo: Eidhoven,
    win: 1,
    draw: 0,
    lose: 0,
    points: 3,
    gf: 3,
    ga: 2,
    gd: 1,
    form: ["w"],
  },
  {
    name: "De Graafschap",
    manager: "romafr_6",
    logo: Graafschap,
    win: 1,
    draw: 0,
    lose: 0,
    points: 3,
    gf: 1,
    ga: 0,
    gd: 1,
    form: ["w"],
  },
  {
    name: "FC Dordrecht",
    manager: "teimuraz",
    logo: Dondrecht,
    win: 1,
    draw: 0,
    lose: 0,
    points: 3,
    gf: 1,
    ga: 0,
    gd: 1,
    form: ["w"],
  },
  {
    name: "Jong FC Utrecht",
    manager: "lashuna",
    logo: Utrecht,
    win: 1,
    draw: 0,
    lose: 0,
    points: 3,
    gf: 1,
    ga: 0,
    gd: 1,
    form: ["w"],
  },
  {
    name: "SC Cambuur",
    manager: "nikaluka_7",
    logo: Cambuur,
    win: 1,
    draw: 0,
    lose: 0,
    points: 3,
    gf: 1,
    ga: 0,
    gd: 1,
    form: ["w"],
  },
  {
    name: "FC Den Bosch",
    manager: "lukanika",
    logo: Bosch,
    win: 0,
    draw: 1,
    lose: 0,
    points: 1,
    gf: 1,
    ga: 1,
    gd: 0,
    form: ["d"],
  },
  {
    name: "VVV-venlo",
    manager: "Mamelodi1",
    logo: Venlo,
    win: 0,
    draw: 1,
    lose: 0,
    points: 1,
    gf: 1,
    ga: 1,
    gd: 0,
    form: ["d"],
  },
  {
    name: "FC Groningen",
    manager: "MR_KAKHA GELADZE",
    logo: Groningen,
    win: 0,
    draw: 0,
    lose: 1,
    points: 0,
    gf: 2,
    ga: 3,
    gd: -1,
    form: ["l"],
  },
  {
    name: "FC Emmen",
    manager: "levani kordzakhia_1",
    logo: Emmen,
    win: 0,
    draw: 0,
    lose: 1,
    points: 0,
    gf: 0,
    ga: 1,
    gd: -1,
    form: ["l"],
  },
  {
    name: "Jong AZ",
    manager: "toklika",
    logo: AZ,
    win: 0,
    draw: 0,
    lose: 1,
    points: 0,
    gf: 0,
    ga: 1,
    gd: -1,
    form: ["l"],
  },
  {
    name: "Telstar",
    manager: "BENZ988",
    logo: Telstar,
    win: 0,
    draw: 0,
    lose: 1,
    points: 0,
    gf: 0,
    ga: 1,
    gd: -1,
    form: ["l"],
  },
  {
    name: "TOP Oss",
    manager: "BayernBeqa999",
    logo: TopOss,
    win: 0,
    draw: 0,
    lose: 1,
    points: 0,
    gf: 0,
    ga: 1,
    gd: -1,
    form: ["l"],
  },
  {
    name: "MVV",
    manager: "Lasha Aleksandriti",
    logo: MVV,
    win: 0,
    draw: 0,
    lose: 1,
    points: 0,
    gf: 1,
    ga: 4,
    gd: -3,
    form: ["l"],
  },
  {
    name: "Willem II",
    manager: "Giko 88",
    logo: Willem,
    win: 0,
    draw: 0,
    lose: 1,
    points: 0,
    gf: 1,
    ga: 5,
    gd: -4,
    form: ["l"],
  },
  {
    name: "ADO Den Haag",
    manager: "GEGIA_G",
    logo: DenHaag,
    win: 0,
    draw: 0,
    lose: 1,
    points: 0,
    gf: 0,
    ga: 4,
    gd: -4,
    form: ["l"],
  },
  {
    name: "Roda JC",
    manager: "guladicha",
    logo: Roda,
    win: 0,
    draw: 0,
    lose: 1,
    points: 0,
    gf: 0,
    ga: 5,
    gd: -5,
    form: ["l"],
  },
];
